### ISSUE TITLE
Can't install OpenMEP

### ISSUE THREAD

**Issue by jacekgrab1** [chuongmep/OpenMEP#21]
OpenMEP was working fine until I instal new Revit 2025 update, basically after the update installation all packages in Dynamo was uninstalled, and I installed all again and also OpenMEP. I install newest OpenMEP but Dynamo not see the OpenMP, I see the "red cross" that Dynamo is telling me that this package is missing, I try older version and the same. Restart also not help. Only I have this issue? 
![image](https://github.com/user-attachments/assets/134ac1ee-cea9-435b-a7da-a6245c7f37b2)

**Comment by chuongmep** [comment]
Hi @jacekgrab1 , thank you for your report, can give me more detail about version revit you are using and dynamo version updated?Also include the list package has installed in your computer to investigate

**Comment by jacekgrab1** [comment]
Dynamo version:
![image](https://github.com/user-attachments/assets/1a3ddebf-1270-44d3-bb78-cb2c46949d9b)
Revit version:
![image](https://github.com/user-attachments/assets/77b234c8-c8c2-4f69-9847-fae63a5a430c)

I have only these packages instaled:
![image](https://github.com/user-attachments/assets/545becf7-4a35-4044-8c47-6a97d1833d60)

**Comment by chuongmep** [comment]
Hi @jacekgrab1 , do you have any warning issue meesage from Dynamo ?

**Comment by jacekgrab1** [comment]
No, basically everything was ok during installation of OpenMEP but Dynamo not see this package and not give any warnings about this. But only I have that isue? But only I have that is issue? OpenMEP works fine for news Revit update for others?

**Comment by chuongmep** [comment]
It's working fine in my computer with base revit 2025, I need check with the latest update of revit 2025 version first, may be in Dynamo version have some patch update

**Comment by chuongmep** [comment]
Look from Revit update release, I saw it have changed with Dynamo Core but not sure which one has changed :https://help.autodesk.com/view/RVT/2025/ENU/?guid=RevitReleaseNotes_2025updates_2025_2_html

Now I'm so busy with my work , I will try take a look on this week.

**Comment by jacekgrab1** [comment]
ok, please let me know if this only my issue or more people has this, I appreciate your commitment with this

**Comment by chuongmep** [comment]
Hi @jacekgrab1 , I just quick fix for it with revit 2025.2 use dynamo 3.2, you can retest with latest version release.
Regard
